ARGOeu/argo-ansible

- roles/pig_client/tasks/main.yml
- standalone.yml
This pull request has been opened as a follow up to [1]. The pig dump exception file path is now configured via ansible. No parameters need to be specified in python script calls. 
[1] https://github.com/ARGOeu/argo-compute-engine/pull/75
please review /cc @pkoro @kaggis
> ARGOeu/ARGO#98 Added role for pig client configuration

- roles/consumer/tasks/main.yml
After renaming the executable script folder standalone -> bin ([see ref]), ansible cron job configurations must be changed to reflect the new path.
[see ref]:https://github.com/ARGOeu/argo-compute-engine/commit/d81f934f5cd5f35d069726d03a22ec39f1a52b50
> Change cron definitions after standalone->bin folder change

- standalone.yml
- webapi.yml
There is no need to define remote username within the playbook as this is set inside the configuration file. However, one needs to define play should run in sudo mode (in case another user is selected via `ansible_user` variable).
> ARGO-242 add sudo true and remove remote username from play

- group_vars/standalone
- group_vars/webapi
- roles/mongodb/defaults/main.yml
- roles/mongodb/tasks/main.yml
Change parameter name `mongo_bind_interface` to plural (`mongo_bind_interfaces`) and give an example within role `defaults`. Should be merged after #31
> ARGO-242 Mongo bind interfaces configuration

- .gitignore
- README.md
- roles/has_certificate/defaults/main.yml
- roles/has_certificate/tasks/main.yml
This changes how key/cert files are handled by the Ansible role has certificate. Public certificate files are made public whereas private key files are ignored from git repo. 
please review /cc @themiszamani
> ARGO-242 Add key files explicitly in gitignore

- roles/consumer/handlers/main.yml
- roles/consumer/tasks/main.yml
- roles/repos/files/etc/yum.repos.d/cloudera-cdh5.repo
Fix in one handler where the old service name was still used and not updated to the new one.
> ARGO-242 Service name has changed

- roles/webui/tasks/main.yml
This is a rather minimal and simple PR. One task is added in order to make sure the cache directory folder exists (in the case a user wants to provide something other than the default, which is `/tmp`). 
> ARGO-290 Make cache directory configurable via vars file

- roles/webui/tasks/main.yml
- roles/webui/templates/lavoisier.csh.j2
- roles/webui/templates/lavoisier.sh.j2
Files copied onto the target host that define the LAVOSIER_HOME env variable are changed to templates instead of files. 
> ARGO-290 Copy source files as templates

- roles/webui/defaults/main.yml
- roles/webui/tasks/main.yml
- roles/webui/templates/argo-config.properties.j2
- roles/webui/templates/lavoisier-hidden.properties.j2
- roles/webui/vars/main.yml
1. Makes API endpoints (ARGO and GocDB) configurable. 
2. Removes `vars/` folder from role (not needed)
> ARGO-242 Changes needed for production web ui deployment

- roles/consumer/tasks/main.yml
A change has been made on the connectors package that allows us to not fetch the complete POEM profiles list that is needed by the prefilter in the usual case. Using this change a flag is conditionally passed onto the related cron job per tenant.
> ARGO-345 Fix in POEM cron job 

- roles/consumer/handlers/main.yml
- roles/consumer/tasks/main.yml
- roles/consumer/templates/consumer.init.j2
A lot of the consumer configuration for the case of the EGI tenant comes straight from the `argo-egi-consumer` ARGO package. This pull request tries to change such basic stuff on the consumer nodes so as not to overwrite such files for the EGI case (only duplicate required files for additional tenants). 
> ARGO-242 Better conditional handling of non egi consumer configurations

- roles/consumer/tasks/main.yml
This change sets the version of the pymongo (installed via pip) package to a specific version. It is suggested so as not to have (in the future) different versions of the specific utility package between devel and production. 
> ARGO-242 Fix pymongo version

- roles/is_monitored/files/ar-dev-api.cfg
- roles/is_monitored/tasks/main.yml
- roles/is_monitored/templates/nrpe.cfg.j2
This PR introduces a change in the nrpe configuration way that is used. 
Instead of copying a file with just one check few more checks are added in the case of a host that acts as an ARGO consumer. Note that this role is not inhereted within any playbook, it is just a utility role as described also in the README.md file. 
> ARGO-356 Modify nrpe configuration workflow

- group_vars/monitoring_engine
- inventory
- monitoring_engine.yml
- roles/monitoring_engine/defaults/main.yml
- roles/monitoring_engine/tasks/main.yml
- roles/monitoring_engine/templates/ncg.conf.j2
- roles/repos/files/etc/yum.repos.d/nagios.repo
- roles/repos/tasks/main.yml
The goal of this PR is to add support for the deployment of the monitoring engines (Nagios) for each tenant.
> ARGO-354 Ansible deploy for monitoring engine

- roles/consumer/templates/consumer.conf.j2
After the latest consumer package update a change needs to be applied in the [configuration template][ref1] used by Ansible. This PR fixes this. 
[ref1]: https://github.com/ARGOeu/argo-egi-consumer/blob/devel/argo-egi-consumer.spec#L67
> ARGO-365 Fix in consumer configuration template

- roles/consumer/files/ar-compute/EGI_JOB_EGI-CLOUDMON-Critical_ap.json
- roles/consumer/files/ar-compute/EGI_JOB_EGI-CLOUDMON-Critical_cfg.json
- roles/consumer/files/ar-compute/EGI_JOB_EGI-OPS-MONITOR-Critical_ap.json
- roles/consumer/files/ar-compute/EGI_JOB_EGI-OPS-MONITOR-Critical_cfg.json
- roles/consumer/files/ar-compute/EGI_JOB_EGI-ROC-Critical_ap.json
- roles/consumer/files/ar-compute/EGI_JOB_EGI-ROC-Critical_cfg.json
- roles/consumer/files/ar-compute/EGI_db_conf.json
- roles/consumer/files/ar-compute/EGI_ops.json
- roles/consumer/files/ar-compute/EUDAT_JOB_ServiceGroups_ap.json
- roles/consumer/files/ar-compute/EUDAT_JOB_ServiceGroups_cfg.json
- roles/consumer/files/ar-compute/EUDAT_db_conf.json
- roles/consumer/files/ar-compute/EUDAT_ops.json
- roles/consumer/files/core-site.xml
- roles/consumer/files/hadoop-env.sh
- roles/consumer/files/hdfs-site.xml
- roles/consumer/files/log4j.properties
- roles/consumer/files/mapred-site.xml
- roles/consumer/files/ssl-client.xml
- roles/consumer/files/topology.map
- roles/consumer/files/topology.py
- roles/consumer/tasks/main.yml
**Usage**:
- Create a soft link in the public repo to private_files dir which is inside argo-ansible-deploy. The directory naming schema is private_files/ansible_fqdn/.
- Include the private file eg. private_files/snf-xxxxx.vm.okeanos.grnet.gr/files/test.conf.j2 in the main task by creating another template in public repo like this: /argo-ansible/roles/consumer/files/test.conf.j2
{% include "private_files/" + ansible_fqdn + "/files/test.conf.j2" %}
Include that template inside ansible's main task 
Full example: https://github.com/grnet/argo-ansible-deploy/pull/24
> Consumer: HADOOP configuration files added with private redirection to private repo

- roles/ingestion_api/tasks/main.yml
- roles/messaging_api/defaults/main.yml
- roles/messaging_api/tasks/main.yml
- roles/messaging_api/templates/init_roles.js.j2
- roles/messaging_api/templates/init_users.js.j2
Add task for initializing users for messaging_api 
Uses the following variable structure:
```
messaging_api_users:
-  username: default_admin
project: ARGO
key: ADMINTOKEN
role: admin
email: admin@argo.example.foo
-  username: default_viewer
project: ARGO
key: VIEWERTOKEN
role: viewer
email: viewer@argo.example.foo
```
- Add Missing subscriptions:pull action in roles
> ARGO-461 Add Task for initializing messaging_api users and keys

- roles/users/tasks/main.yml
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax
> Users: Removed  messages about deprecation.

- roles/users/tasks/main.yml
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax
> Users: Removed  messages about deprecation. 

- roles/timezone/tasks/main.yml
Updated the timezone role from timezone to command to match the current ansible version.
> ARGO-524 - Timezone module is not available in the ansible version we use

- roles/firewall/tasks/centos7.yml
The ansible script does not restart the firewall and thus https is filtered although the configuration is there. I updated the ansible script to restart firewall for centos7.
> [ARGO-527] - The ansible script does not properly allow traffic for https

- roles/messaging_api/templates/init_roles.js.j2
AMS: Users with 'consumer' role should be able to call subscription:acknowledge
Add 'consumer' role to 'subscription:acknowledge' resource in init_roles template script
> AMS: mongo: add consumer role to subscription acknowledge action

- roles/swagger/tasks/main.yml
Point swagger-ui to corresponding swagger definitions on host action. 
The index file has changed so we had to update the regex.
> ARGO-787 - Swagger - Apis error

- roles/messaging_api/templates/init_roles.js.j2
Updates the script that initializes the roles in mongodb
the collection containing the role definitions is named `roles`
Each entry in the mongodb `roles` collection has a pair of values `{ resource: '', roles: ''}`
- `resource` describes the name of the route 
- `roles` is an array containing role names (strings) that are eligible to access this route
Changes are made to the metric related roles which are mapped to the following resource definitions:
- `topics:metrics`
- `subscriptions:metrics`
- `projects:metrics`
- `ams:metrics` : general operational metrics for the ams service
> ams: Update metric-related roles in mongodb

- roles/zookeeper/tasks/main.yml
- roles/zookeeper/templates/java.env.j2
Zookeeper use of java.env at conf folder to export and enable java options
> ARGO-876: Create java.env to host JAVA_OPTIONS

- roles/kafka/templates/kafka.service.j2
Use 'KAFKA_OPTS' env variable for extra java options during kafka start-up
Use -Djava.net.preferIpv4Stack for prefering ipv4 sockets in systems where ipv6 is available
Declare the option in kafka.service file as an additional Enviroment parameter
> Add kafka java parameter for ipv4 interface preference

- roles/kafka/defaults/main.yml
- roles/kafka/templates/server.properties.j2
a) Added a new  kafka group to inventory.
b) in server.properties i count the number of servers in kafka group and if it is > 3 then replication factor is 3, otherwise it is set to 1.
> [kafka] - added replication factor dynamically

- roles/has_certificate/defaults/main.yml
- roles/has_certificate/tasks/main.yml
- Ensure haproxy user:group exists before chmod certificate
- Ensure default path `/var/www/argo-messaging/` is defined when creating link files to certificates for argo-messaging
> Refactor has_certificate for haproxy and argo-messaging cert placement

- roles/kafka/tasks/main.yml
Add same firewall rule command structure as in web_api_v2 into kafka role so as not to disturb previous roles used in playbook
- Ability to specify zones
- Ability to specify services
- Ability to specify sources
- Ability to add services to zones, and interfaces to zones
> ARGO-1025 Firewall rules for accessing ams kafka service

- roles/haproxy/templates/haproxy_template.cfg.j2
In haproxy.cfg, change bind statements from `*:port --> :::port` (for supporting both ipv6 and ipv4)
> Update haproxy cfg bind for both ipv4/6

- roles/haproxy/defaults/main.yml
- roles/haproxy/templates/haproxy_template.cfg.j2
Add section for using authn backend in haproxy
- add configurable `authn_host` and `authn_port` in ansible host vars
- declare authn backend to haproxy.cfg.template
- add rule for using authn backend (when url path begins with `/authn`)
> Add authn redirect to haproxy cfg template

- roles/repos/tasks/main.yml
- roles/webapi_v2/tasks/deploy.yml
- roles/webapi_v2/templates/init_users.js.j2
- webapi_v2_deploy.yml
- Refactor repos role to install mongodb 3.2 when api is deployed
- Remove `when var is defined rules` from firewall tasks and use empty list instead (when variables should not be defined)
- Refactor tasks that move certificates for argo-web-api service
- Refactor permissions in folders used by argo-web-api service
- Fix typo in init users script for mongodb
- Add selinux role
> AO-364 Fixes in argo-web-api v2 deployment

- roles/commons/README.md
- roles/commons/defaults/main.yml
- roles/commons/handlers/main.yml
- roles/commons/tasks/firewall.yml
- Firewall role now declares unmanaged interfaces from NetworkManager
- Firewall role can now reset FirewallD to initial Centos7 deployment settings
- Add Firewalld service restart handler
> Update firewall role

- install.yml
- roles/commons/files/etc/yum.repos.d/cloudera-kafka.repo
- roles/kafka/.yamllint
- roles/kafka/README.md
- roles/kafka/defaults/main.yml
- roles/kafka/handlers/main.yml
- roles/kafka/meta/main.yml
- roles/kafka/molecule/default/Dockerfile.j2
- roles/kafka/molecule/default/INSTALL.rst
- roles/kafka/molecule/default/molecule.yml
- roles/kafka/molecule/default/playbook.yml
- roles/kafka/molecule/default/tests/test_default.py
- roles/kafka/tasks/main.yml
- roles/kafka/templates/server.properties.j2
- roles/kafka/vars/main.yml
- Use cloudera kafka repo to install kafka through rpm 
- Needs an existing zookeeper cluster (or to be run after zookeeper role)
- depends on the following host_vars:
repo_cloudera_kafka: true (must be enabled so as to get cloudera kafka repo when commons/repos task executes)
kafka_broker_id: fill broker id (unique for each node)
kafka_zookeeper_connect: list of zk hosts (`host1:2181,host2:2181,host3:2181`) to connect to
- apply linting
- update readme
> Add kafka role

- roles/ams/templates/db_init_roles.js.j2
- Update initialization of ams roles in database:
- make GET user by uuid accessible for `service_admin` and `argo_api_authn` roles
- make GET metrics accessible for `service_admin` and `metrics_viewer` roles
> Update ams roles for argo-api-authn and metrics-ui

- install.yml
- roles/ams/tasks/deploy.yml
- roles/commons/defaults/main.yml
- roles/commons/tasks/firewall.yml
- roles/commons/tasks/repos.yml
- roles/kafka/templates/server.properties.j2
- roles/mongodb/README.md
- roles/mongodb/defaults/main.yml
- roles/mongodb/tasks/main.yml
- roles/mongodb/templates/db_init_rs.js.j2
- roles/mongodb/templates/db_rs_members.js.j2
- roles/mongodb/templates/mongod.conf.j2
- roles/zookeeper/tasks/main.yml
- Change mongo config from line-in-file edits to complete template
- Fix: ams service enabled to true
- Use mongo_replicated boolean as a replication conditional in deployments
- Use a different data folder (/var/lib/mongo_repl) when replication is enabled
- Use db_rs_init and db_rs_members javascript scripts to initiate replication set and group members
- add zktop, motop utilities
> Add replicated mongo setup

- roles/commons/README.md
- roles/commons/tasks/repos.yml
- Use nmcli to get connection uuids for declared private interfaces (declared as list in `{{firewall_private_interfaces}}` var)
- Register connection uuids to an ansible variable 
- Use ansible variable with connection uuids in nmcli to set connection.zone to internal
- update readme
Other Fixes:
- cloudera-kafka repo 
- use private_hosts role in ams_store group
> AO-380 Configure internal zone in Network Manager

- roles/kafka/README.md
- roles/kafka/defaults/main.yml
- roles/kafka/templates/server.properties.j2
Use a variable to speciy kafka log directories. (Comma separated list of paths)
default value = '/var/lib/kafka'
> AO-405 Specify kafka log dirs

- roles/alerta/defaults/main.yml
- roles/alerta/tasks/deploy.yml
- roles/alerta/templates/supervisord.conf.j2
Fixes:
- Correctly place argo-mailer configurations in subfolder named `mail-{tenant}`
- Replace cp with synchronize module when deploying alerta-ui static files 
- Add alerta_token tag to easily re-run a subset of tasks when changing admin tokens
> ARGO-1889 Minor fixes in alerta role

- roles/commons/handlers/main.yml
There is a problem with the [**listen**](https://github.com/ARGOeu/argo-ansible/blob/ansible2.9/roles/commons/handlers/main.yml#L9) command, which creates continuous - unnecessary - reboots of the fail2ban service.
**EXPECTED RESULTS**
<details>
<summary> Output: </summary>
```
......................
TASK [commons : Install rsyslog gnutls] ***************************************************************************************************************************************************************************
changed: [centOS1-Knossos]
TASK [commons : Rsyslog conf file] ********************************************************************************************************************************************************************************
changed: [centOS1-Knossos]
TASK [commons : …
```
> DEVOPS-51 Fix the problem of restarting fail2ban service.

- roles/disable_ipv6/tasks/main.yml
Because of this warning :
```
[WARNING]: The value 1 (type int) in a string field was converted to u'1' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
```
> DEVOPS-39 Migration tests of the role disable_ipv6 in Ansible 2.9.3

- roles/argo-api-authn/tasks/python-env-setup.yml
Because the **virtualenv** package was installed by pip**2** rather than pip**3.6**, this caused the following problem:
```bash
TASK [argo-api-authn : Create a virtualenv and install the requirements] *******************************************************************
fatal: [centos7_devel_1]: FAILED! => changed=false 
invocation:
module_args:
chdir: null
editable: false
executable: null
extra_args: null
name:
- git+https://github.com/ARGOeu/argo-api-authn.git@devel#egg=argo-api-authn-scripts
requirements: null
state: present
umask: null
version: null
virtualenv: /opt/virtualenv/authn-env
virtualenv_command: virtualenv
virtualenv_python: python3.6
virtualenv_site_packages: false
msg: |-
Could not get output from /usr/bin/virtualenv --help: Traceback (most recent call last):
File …
```
> DEVOPS-34 Migration tests of the role argo-api-authn in Ansible 2.9.3

- roles/metrics/tasks/ce_comp.yml
Because of the following `FAILED` & `WARNING`:
```
TASK [metrics : Create a virtualenv for the script] ***************************************************************************************************************************************************************
fatal: [centos7-metricsVM]: FAILED! => changed=false 
msg: |-
Could not get output from /usr/bin/virtualenv --help: Traceback (most recent call last):
File "/usr/bin/virtualenv", line 7, in <module>
from virtualenv.__main__ import run_with_catch
File "/usr/lib/python2.7/site-packages/virtualenv/__init__.py", line 3, in <module>
from .run import cli_run
File "/usr/lib/python2.7/site-packages/virtualenv/run/__init__.py", line 12, in <module>
from .plugin.activators import ActivationSelector
File …
```
> DEVOPS-41 Migration tests of the role metrics in Ansible 2.9.3

- roles/webapi/tasks/deploy.yml
In Ansible 2.9.3 the syntax has changed slightly.
I have this error with the existing implementation :
```
TASK [webapi : Setup argo-web-api service] **********************************************
changed: [centos7-argo-web-api]
TASK [webapi : reload systemd] **********************************************
fatal: [centos7-argo-web-api]: FAILED! => 
msg: |-
The conditional check 'argowebapi_service | changed' failed. The error was: template error while templating string: no filter named 'changed'. String: {% if argowebapi_service | changed %} True {% else %} False {% endif %}
The error appears to be in '/home/tas-sos/workspace/ansible/argo-ansible-deploy/argo-ansible/roles/webapi/tasks/deploy.yml': line 32, column 3, but may
be elsewhere in the file depending on the exact syntax problem. …
```
> DEVOPS-49 Migration tests of the role webapi in Ansible 2.9.3

- roles/alerta/defaults/main.yml
- roles/alerta/files/uwsgi.service
- roles/alerta/tasks/deploy.yml
- roles/alerta/templates/supervisord.conf.j2
```bash
[WARNING]: While constructing a mapping from ...../argo-ansible-deploy/argo-ansible/roles/alerta/defaults/main.yml, line 40, column 5, found a duplicate dict key (ui_endpoint). Using
last defined value only.
```
[  [pip install virtualenv broken / missing zipp package #1630](https://github.com/pypa/virtualenv/issues/1630)  ]
```bash
TASK [alerta : Install Alerta] *********************************************************************************************************
fatal: [centos7_devel_2]: FAILED! => changed=false 
msg: |-
Could not get output from /usr/bin/virtualenv --help: Traceback (most recent call last):
File "/usr/bin/virtualenv", line 7, in <module>
from virtualenv.__main__ import run_with_catch
File "/usr/lib/python2.7/site-packages/virtualenv/__init__.py", line 3, in …
```
> DEVOPS-31 Migration tests of the role alerta in Ansible 2.9.3

- roles/flink/tasks/main.yml
Changes to eliminate the following warnings :
```
TASK [flink : Remove older downloaded flink] **********************************************************************************************************************************************************************
[WARNING]: Consider using the file module with state=absent rather than running 'rm'.  If you need to use command because file is insufficient you can add 'warn: false' to this command task or set
'command_warnings=False' in ansible.cfg to get rid of this message.
```
```
TASK [flink : Unpack tarball] *************************************************************************************************************************************************************************************
[WARNING]: Consider using the unarchive module …
```
> DEVOPS-40 Migration tests of the role flink in Ansible 2.9.3

- roles/swagger/files/var/www/html/index.html
- roles/swagger/templates/index.html.j2
Replace http links with https because firefox sets a warning for unsafe objects in this page.
> DEVOPS-244 Move links to https

- roles/icinga_agent/tasks/common_Debian.yml
- roles/icinga_agent/tasks/common_RedHat.yml
Add argo-external-tools installation icinga agent role.
On debian we can't use the rpm package so we decided to downloaded to the nagios/plugins folder directly wit get_url
> Add installation of external tools

- roles/haproxy/defaults/main.yml
- roles/haproxy/templates/haproxy_template.cfg.j2
Update the haproxy template to have a configurable variable for frontend HTTP time out requests with a default value fo 10 seconds
> ARGO-2761 Update HAproxy vars with new timeout value

- roles/apache/handlers/main.yml
We also need to enable httpd so that it starts automatically when the system starts.
> Enable httpd.

- roles/apache/tasks/backup.yml
- roles/apache/templates/virtualhost.j2
- roles/commons/tasks/cert.yml
Some bug fixes for the Apache role focused on certificate transfer.
_With existing code and using Ansible v**2.9.11**, the `requires_cert` variable wasn't evaluated correctly._
> Apache: Fixed some issues with certificates.

- roles/commons/tasks/repos.yml
- roles/icinga_agent/tasks/common_RedHat.yml
We need to install `percona` repositories and `percona-nagios-plugins` only when : 
`repo_mongo_4x == True   or  repo_mongo == True`
These variables are set to `False` by **default** ( is defined ) : https://github.com/ARGOeu/argo-ansible/blob/devel/roles/commons/defaults/main.yml#L27-L28
> Fix percona mongodb probe.

- install.yml
The following PR introduces the following changes.
- Use the new apache role for apache set up
- Use tags for a more convenient installation when we update just the swagger files
> Use new apache role and add tags

- install.yml
- roles/mongodb/README.md
- roles/mongodb/defaults/main.yml
- roles/mongodb/tasks/main.yml
- roles/mongodb/templates/db_rs_members.js.j2
- roles/mongodb/templates/mongodb_backup.sh.j2
Introduce some new tasks that will take care of taking regular backups of the mongodb databases that we have in the devel cluster.
Introduce the backup script that can run for multiple databases.
Introduce a new variable, mongo_cluster_group specifically for grouping mongodb nodes.
mongo_backup_scripts_location variable for the location of the back up script
mongo_replica_set_name variable that controls the name of the replica set
mongo_backup_dbs: list variable that names the mongo databases that we want to backup.
> ARGO-2895 AMS devel mongodb backup

- roles/commons/defaults/main.yml
- roles/commons/tasks/rsyslog.yml
- roles/commons/templates/50_client_remote.conf.j2
To be as safe as possible, we will transfer the certificates for rsyslog client to the remote machines in a **completely separate directory** and with a very **specific name**.
So, by default we will have the following results:
* `/etc/rsyslog.d/50_client_remote.conf`
```
$DefaultNetstreamDriver gtls
$DefaultNetstreamDriverCAFile /etc/grid-security/rsyslog-client-certs/rsyslog_chain.crt
$DefaultNetstreamDriverCertFile /etc/grid-security/rsyslog-client-certs/rsyslog.crt
$DefaultNetstreamDriverKeyFile /etc/grid-security/rsyslog-client-certs/rsyslog.key
#$ModLoad imtcp  # TCP listener
$ActionSendStreamDriverAuthMode x509/name
$ActionSendStreamDriverPermittedPeer *.argo.grnet.gr
$ActionSendStreamDriverMode 1 # run driver in TLS-only mode
*.* @@rsyslog.argo.grnet.gr:6514;RSYSLOG_ForwardFormat …
```
> Separate directory for rsyslog certificates.

- roles/ams/templates/db_init_pushworker.js.j2
Update the push_worker init template to only initialize the projects empty array when being inserted for the first time.
Otherwise, every time we run the task, the push worker gets emptied from its projects.
Complementary also added valid ways to update the created_on and modified_on fields.
> ARGO-2975 ams ansible role: update push_worker init template

- roles/argo-api-authn/tasks/python-env-setup.yml
System prerequisites in order to install python-ldap=3.3.1 that will be added to the scripts environment
> ARGO-3061 authn role: Install the ldap prerequisites

- roles/apache/README.md
- roles/apache/defaults/main.yml
- roles/apache/tasks/install.yml
Now we can also install and enable/disable apache (httpd) modules only using the following list variables:
> DEVOPS-415: Apache/enable disable modules

- roles/haproxy/defaults/main.yml
------------------
Jenkins jobs: 
* https://jenkins.einfra.grnet.gr/job/ARGO-utils/job/deploy-gr.grnet.eseal/27/ :x: 
* https://jenkins.einfra.grnet.gr/job/ARGO-utils/job/deploy-gr.grnet.eseal/28/ :x:
> Fix: Add quotes.

- roles/eseal/tasks/main.yml
The until - retry is called `until loop` https://www.ansible.com/blog/ansible-tips-and-tricks-dealing-with-unreliable-connections-and-services and those arguments should be both present to be able to retry the command in the specific module.
> Set until argument after retries

- roles/ams/templates/config.json.j2
- roles/kafka/templates/server.properties.j2
- roles/zookeeper/templates/zoo.cfg.j2
The variable `zookeeper_group` already exists in the [zookeeper role](https://github.com/ARGOeu/argo-ansible/tree/devel/roles/zookeeper). 
* https://github.com/ARGOeu/argo-ansible/blob/e071c4d2ea347a7a986ff99a7374cc69763a5bfb/roles/zookeeper/tasks/config.yml#L7-L30
* https://github.com/ARGOeu/argo-ansible/blob/e071c4d2ea347a7a986ff99a7374cc69763a5bfb/roles/zookeeper/defaults/main.yml#L40-L41
and in https://github.com/grnet/argo-ansible-deploy/blob/43bce4ecd45cf38759939813722dfe89cefe0b15/group_vars/ams_cluster#L12
So, in order to avoid confusion, I renamed this variable to `zookeeper_cluster_group`.
----------
* :link: https://github.com/grnet/argo-ansible-deploy/pull/336 :warning:
> Fix zookeeper logs and configuration.

- roles/kafka/tasks/config.yml
- roles/kafka/tasks/kafka.yml
- roles/zookeeper/tasks/config.yml
- roles/zookeeper/tasks/zookeeper.yml
> DEVOPS-469 : Zookeeper & Kafka /etc/ configuration paths.

- roles/icinga_agent/README.md
- roles/icinga_agent/defaults/main.yml
- roles/icinga_agent/handlers/main.yml
- roles/icinga_agent/tasks/agent.yml
- roles/icinga_agent/tasks/common_RedHat.yml
Now we can run icinga agent for different Icinga masters like bellow:
* Example 1:
```
ansible-playbook -i production argo-ansible/install.yml \
-e "icinga_master_domain=icinga-1.master.example.com client_pki_ticket_token=123456789" \
--ssh-common-args='-o StrictHostKeyChecking=no' -vv
```
* Example 2:
```
ansible-playbook -i production argo-ansible/install.yml \
-e "icinga_master_domain=icinga-2.master.example.com client_pki_ticket_token=abcdef" \
--ssh-common-args='-o StrictHostKeyChecking=no' -vv
```
> Improvements for different Icinga master setups.

- roles/commons/tasks/rsyslog.yml
- roles/commons/templates/etc/rsyslog.d/50_client_remote.conf.j2
Improvements to be able to support different/general certificates.
Now, regardless of the certificate ( domain specific, star certificate etc.. ), all that is needed is to be placed with the following names:
* `private_files/{{ inventory_hostname }}/rsyslog-gnutls/rsyslog-cert.pem`
* `private_files/{{ inventory_hostname }}/rsyslog-gnutls/rsyslog-key.pem`
* `private_files/{{ inventory_hostname }}/rsyslog-gnutls/rsyslog-ca.pem`
```
ansible-playbook -i devel argo-ansible/install.yml -vv --tags="repos, rsyslog_conf" --list-hosts --list-tasks
```
> Rsyslog client improvements.

- roles/argo-api-authn/tasks/update.yml
As in the installation process, we also want the UUID of AMS service type.
So, now we can also use the update playbook : https://github.com/ARGOeu/argo-ansible/blob/devel/update.yml#L8-L14
* https://jenkins.einfra.grnet.gr/job/ARGO-utils/job/deploy-argo-api-authn/46/console
> argo-api-authn/tasks/update.yml: Get the uuid

- roles/swagger/tasks/main.yml
Set version of PyYaml to the latest that supports python2. We run the job in python2 environment this should be a temporary fix and later we should migrate everything to python3
> Freeze pyyaml version

- roles/mongodb/tasks/main.yml
<details>
<summary>Before :x:  </summary>
```bash
TASK [mongodb : install motop] ***********************************************************************************************************************************************
task path: /ansible/argo-ansible-deploy/argo-ansible/roles/mongodb/tasks/main.yml:27
fatal: [mongo-probe-test]: FAILED! => changed=false 
cmd:
- /usr/bin/pip2.7
- install
- git+https://github.com/tart/motop.git
msg: |-
stdout: Collecting git+https://github.com/tart/motop.git
Cloning https://github.com/tart/motop.git to ./pip-xOYWmb-build
Collecting pymongo (from motop==4.2)
Downloading https://files.pythonhosted.org/packages/3f/ff/7ec17064d403799d644f7db9c2e99202441849aebe771efe3199f3dd9076/pymongo-4.0.1.tar.gz (768kB)
Complete output from command python setup.py …
```
> Install motop only with Python 2.7 & pip2.7

- roles/commons/tasks/firewall.yml
<details>
<summary>Before :x:  </summary>
```bash
TASK [commons : Create firewall new zones] *******************************************************************************************
task path: /ansible/argo-ansible-deploy/argo-ansible/roles/commons/tasks/firewall.yml:42
failed: [test_vm] (item=icinga) => changed=true 
ansible_loop_var: item
cmd:
- firewall-cmd
- --permanent
- --new-zone=icinga
delta: '0:00:00.442815'
end: '2022-01-21 13:19:38.281205'
item: icinga
msg: non-zero return code
rc: 26
start: '2022-01-21 13:19:37.838390'
stderr: 'Error: NAME_CONFLICT: new_zone(): ''icinga'''
stderr_lines: <omitted>
stdout: ''
stdout_lines: <omitted>
...ignoring
```
```bash
TASK [commons : Create firewall new services] **************************************************************************** …
```
> DEVOPS-467 : Fix failed_when in firewalld tasks.

- ams-cluster-playbook.yml
- roles/ams/tasks/deploy.yml
- roles/ams/templates/config.json.j2
- roles/haproxy/templates/haproxy_template.cfg.j2
- roles/mongodb/tasks/main.yml
> Fixes when we deploy AMS cluster without push server.

- roles/haproxy/templates/haproxy_template.cfg.j2
> DEVOPS-583 HAProxy: no-tlsv10 no-tlsv11

- roles/accounting/tasks/main.yml
Related
=========================================
* https://github.com/ARGOeu/argo-ansible/pull/504
* https://github.com/grnet/argo-ansible-deploy/pull/375
* https://github.com/ARGOeu/ARGO-accounting/pull/20
> DEVOPS-591 Disable Accounting API checks.

- roles/rseval/files/.env
Related to latest update (https://github.com/ARGOeu/eosc-recommender-metrics/pull/119) that shortens the env var names
> REC-199 RSeval role update default env vars

- rseval-playbook.yml
Due to issues with mongo 4.4 and the current mongo role, temporarily deactivate mongo role from rseval playbook
> Temporarily deactivate mongo role in rseval playbook

- roles/frontend/defaults/main.yml
- roles/frontend/handlers/main.yml
- roles/frontend/tasks/main.yml
- roles/frontend/tasks/react-based.yml
Add a generic frontend role to deploy frontend/ui builds.
Frontend role has a specific task file: `react-based.yml` that implements a simple react/nodejs ui build deployment. Others can be added in the future
> PIDMR-45 Create ansible role for frontend deployments

- roles/frontend/defaults/main.yml
- roles/frontend/tasks/react-based.yml
Update frontend react deploy task to add build information to the produced artifact. This requires to gather the following information:
- github repo used: This is already stored in `checkout_repo` ansible var (need some regex manipulation to produce `http://gitub.com/org/repo/tree/{commit}`
- github commit hash: This is retrieved in a new task and stored to the `build_commit_hash` variable
- build date: This is calculated in a new task and stored in iso format in the var `build_date`
> CAT-85 Add version and build info in frontend role
