ARGOeu/argo-ansible

roles/consumer/files/customer.conf
roles/consumer/tasks/main.yml
roles/consumer/templates/consumer.conf.j2
roles/mongodb/tasks/main.yml

- customer.con updated
- consumer config as template to allow virtual queues.
- fix in package name (`ar-consumer` -> `argo-egi-consumer`)

ARGO-241 Updates in roles

---

roles/repos/files/etc/yum.repos.d/cloudera-cdh5.repo
roles/repos/tasks/main.yml

Use cdh5 henceforth. 
please review /cc @themiszamani @kaggis

Install cdh5 repo henceforth

---

roles/mongodb/tasks/main.yml

Explicitly define which mongo version to install and use.

ARGO-242 ARGO-287 Mongo configuration

---

README.md
inventory
roles/firewall/tasks/centos6.yml
roles/firewall/tasks/centos7.yml
roles/firewall/tasks/main.yml
roles/has_certificate/tasks/main.yml
roles/repos/tasks/main.yml
roles/webui/defaults/main.yml
roles/webui/files/lavoisier.csh
roles/webui/files/lavoisier.sh
roles/webui/handlers/main.yml
roles/webui/tasks/main.yml
roles/webui/vars/main.yml
webui.yml

This PR translates the [web ui setup guide][l1] into Ansible role and play. 
The PR is currently in WIP state because an error is generated when trying to start the service. The error is [here][l2]. An initial investigation has began and if appropriate an issue will be opened to update the guide. 
[l1]: https://github.com/ARGOeu/argo-egi-web
[l2]: http://fpaste.org/288834/14471658/raw/

ARGO-243 WebUI Role addition

---

roles/webapi/handlers/main.yml
roles/webapi/tasks/main.yml

Both package and service name have changed from `ar-web-api` to `argo-web-api`. This PR handles this change.

ARGO-242 Package and service rename

---

group_vars/all
roles/consumer/tasks/main.yml
roles/repos/defaults/main.yml
roles/repos/files/etc/yum.repos.d/argo.repo
roles/repos/tasks/main.yml
roles/webapi/tasks/main.yml

Minor change that makes the repos role a bit more readable. WIP for the time being.

ARGO-242 Simplify vars and callout in yum module

---

README.md
roles/is_monitored/defaults/main.yml
roles/is_monitored/files/ar-dev-api.cfg
roles/is_monitored/handlers/main.yml
roles/is_monitored/tasks/main.yml

This PR intends to encapsulate all changes needed in order to use this repo as the primary repo to deploy our DEVEL and PROD services.

ARGO-242 Adds nagios nrpe integration as role

---

README.md
roles/webui/defaults/main.yml
roles/webui/handlers/main.yml
roles/webui/tasks/main.yml

Using this commit one can configure which (tenant-wise) web ui to deploy onto a target host. A small update in the readme file is included for easier reviewing. 
Please review /cc @themiszamani

ARGO-308 Make web ui tenant configurable

---

roles/consumer/defaults/main.yml
roles/consumer/tasks/main.yml
roles/consumer/templates/ar-compute-engine.conf.j2
roles/consumer/templates/consumer.conf.j2

Change in CE configuration manipulation. Instead of multiple lineinfile commands a template is used. 

ARGO-242 Change CE configuration to template

---

roles/repos/files/etc/yum.repos.d/cloudera-cdh5.repo

Minor changes in the cloudera yum repository definitions file.

ARGO-242 Minor fixes in Cloudera repository definition file

---

roles/consumer/tasks/main.yml

Just a small typo fix I noticed while working on something else. 

Typo fix in task name

---

roles/consumer/templates/poem-connector.conf.j2

Remove eudat specific poem profile from prefiltering section (concerns only egi tenant)

ARGO-242 Remove eudat profile from egi prefilter section

---

roles/consumer/defaults/main.yml
roles/consumer/templates/customer.conf.j2

I noticed this typo while testing the playbooks. 

ARGO-242 Fix typo in customer template

---

roles/consumer/tasks/main.yml

New task added that creates and configures the weights cron jobs on a per tenant basis

ARGO-358 Deploy weights cron jobs per tenant

---

README.md

Update of README file in order to include more specific details on how to overwrite the default variable values given inside the roles. 
please review /cc @themiszamani

ARGO-356 Update README with guidance on variables values overwriting

---

roles/consumer/templates/consumer.conf.j2

Update in consumer template configuration file. Relates to https://github.com/ARGOeu/argo-egi-consumer/pull/30

ARGO-365 New configuration templates for consumer and connectors

---

roles/webui/defaults/main.yml
roles/webui/templates/argo-config.properties.j2

Modify template of configuration file for Lavoisier Web UI based on recent changes made on the argo-eudat-web sources.

ARGO-351 Update lavoisier configuration file templating

---

roles/monitoring_engine/defaults/main.yml
roles/monitoring_engine/tasks/main.yml
roles/monitoring_engine/templates/broker-list.j2
roles/monitoring_engine/templates/nagios.cfg.j2
roles/monitoring_engine/templates/ncg.conf.j2

ARGO-354 Added ncg and nagios configs.

---

group_vars/monitoring_engine
monitoring_engine.yml
roles/monitoring_engine/tasks/main.yml

ARGO-354 Ansible installation actions for monitoring engine

---

roles/webapi/defaults/main.yml
roles/webapi/handlers/main.yml
roles/webapi/tasks/main.yml
roles/webapi/templates/argo-web-api.conf.j2

Adds a template task within the web api role. It is handy (and needed) for deploying onto the swagger UI interface. In the regular case nothing changes. 

Add template action within argo-web-api role

---

roles/webapi/defaults/main.yml
roles/webapi/templates/argo-web-api.conf.j2

ARGO-391 Make port web api is running on configurable

---

roles/webapi/tasks/main.yml

ARGO-391 Fix in Ansible template task

---

roles/monitoring_engine/tasks/main.yml
roles/monitoring_engine/templates/ncg.conf.j2

Add installation action for UMD based nagios plugins

ARGO-389 Central nagios UMD plugins

---

roles/monitoring_engine/defaults/main.yml
roles/monitoring_engine/templates/nagios.cfg.j2
roles/repos/tasks/main.yml

- Modified nagios.cfg template
- Added more default vars for nagios configuration
- Added umd repo installation action

ARGO-389 Added nagios.cfg related vars. Added umd repo installation action

---

roles/swagger/defaults/main.yml
roles/swagger/handlers/main.yml
roles/swagger/tasks/main.yml

ARGO-393 Changes in swagger role

---

roles/webapi/defaults/main.yml
roles/webapi/templates/argo-web-api.conf.j2

Change in variable name. Make it more specific.

Make variable name more specific

---

roles/monitoring_engine/defaults/main.yml
roles/monitoring_engine/tasks/main.yml
roles/monitoring_engine/templates/ucc.config.j2
roles/monitoring_engine/templates/unicore_jks.sh.j2
roles/monitoring_engine/templates/unicore_ks.sh.j2
roles/monitoring_engine/templates/unicore_ts.sh.j2

Added scripts for the creation of unicore credentials
Added templates for private files

ARGO-389 Ansible configurations for unicore probes

---

roles/monitoring_engine/tasks/main.yml
roles/monitoring_engine/templates/ncg.conf.j2

Add robot certificate configuration in NCG. Enable msg handler on boot

---

messaging_api.yml
roles/messaging_api/defaults/main.yml
roles/messaging_api/handlers/main.yml
roles/messaging_api/tasks/main.yml
roles/messaging_api/templates/config.json.j2

Add ARGO messaging api role and playbook

Add ARGO messaging api role

---

messaging_api.yml

Fix messaging host reference and tags

Fix messaging host reference and tags

---

roles/consumer/defaults/main.yml
roles/consumer/templates/consumer.conf.j2

The data are usually stored to /var/lib/. On the devel vm we added a volume and the data are stored to /mnt/data/

Add new paremeter to defauls data_path. 

---

roles/consumer/templates/ar-compute-engine.conf.j2

Add consumers root path parameter to configuration

ARGO-455 Add consumer root path to compute engine configuration

---

messaging_api.yml
roles/kafka/defaults/main.yml
roles/kafka/handlers/main.yml
roles/kafka/tasks/main.yml
roles/kafka/templates/kafka.service.j2
roles/kafka/templates/log4j.properties.j2
roles/kafka/templates/server.properties.j2
roles/messaging_api/defaults/main.yml
roles/messaging_api/tasks/main.yml
roles/messaging_api/templates/config.json.j2
roles/messaging_api/templates/init_defaults.js.j2
roles/zookeeper/defaults/main.yml
roles/zookeeper/handlers/main.yml
roles/zookeeper/tasks/main.yml
roles/zookeeper/templates/environment.j2
roles/zookeeper/templates/log4j.properties.j2
roles/zookeeper/templates/myid.j2
roles/zookeeper/templates/zoo.cfg.j2
roles/zookeeper/templates/zookeeper.service.j2

ARGO-449 Add Zookeeper and Kafka roles

---

roles/messaging_api/tasks/main.yml
roles/mongodb/tasks/main.yml
roles/repos/files/etc/yum.repos.d/mongodb-org-3.2.repo
roles/repos/tasks/main.yml

Fix mongodb repo and deployment.

---

roles/kafka/tasks/main.yml
roles/zookeeper/tasks/main.yml

Kafka , zookeeper roles: Updated the destination folder where the files are downloaded due to permission error. Remove older downloaded files

Kafka , zookeeper roles updates to downloaded files 

---

roles/has_certificate/tasks/main.yml
roles/repos/files/etc/yum.repos.d/argo-centos7.repo
roles/repos/files/etc/yum.repos.d/argo.repo
roles/repos/tasks/main.yml

- has_certificate role: Remove old p12 key for web ui.
- Repos: add centos7 yum repo

Changes To roles

---

roles/kafka/defaults/main.yml
roles/messaging_api/tasks/clear.yml
roles/messaging_api/tasks/stop_push_subs.yml

ARGO-488 Clear Messaging-API services

---

roles/messaging_api/tasks/clear.yml
roles/messaging_api/tasks/deploy.yml

a) added a sleep 40 instead of 15. 
b) Added systemctl deamon-reload to avoid the warning .

Messaging Role updates

---

roles/messaging_api/defaults/main.yml
roles/messaging_api/templates/init_users.js.j2

Fix users definition to use project_uuid instead of project name

Fix messaging users definitions to use project_uuid

---

roles/messaging_api/defaults/main.yml
roles/messaging_api/templates/init_users.js.j2

Add missing uuids from user definitions in messaging-api

Add uuids in messaging user definitions

---

roles/messaging_api/templates/init_projects.js.j2

- Update "created_on", "modified_on" date field during initialization

ARGO-589 Add project creation,modified dates during initialization

---

README.md
roles/is_monitored/defaults/main.yml
roles/is_monitored/tasks/main.yml

add firewall cmd rule to open port only for monitoring host

[is_monitored]: add firewall cmd rule 

---

README.md
messaging_api.yml
roles/consumer/tasks/deploy.yml
roles/has_certificate/tasks/main.yml
roles/messaging_api/tasks/deploy.yml
roles/messaging_api/templates/config.json.j2
roles/zookeeper/handlers/main.yml
roles/zookeeper/tasks/main.yml
template_hostvars/messaging.yml

[AO-160]-[Messaging API]: Changes to support messaging service deployment. [ARGO-523], [ARGO-526]

[AO-160]-[Messaging API]:  [ARGO-523], [ARGO-526] Changes to support messaging service deploment

---

roles/messaging_api/defaults/main.yml
roles/messaging_api/templates/config.json.j2

Update config template with latest parameters. Update defaults

Update argo-messaging config template and defaults

---

roles/webui/templates/lavoisier-hidden.properties.j2

Lavoisier Hidden, added from email used for recomputations.

---

roles/flink/defaults/main.yml
roles/flink/handlers/main.yml
roles/flink/tasks/main.yml
roles/flink/templates/flink-conf.yaml.j2
roles/flink/templates/hosts.j2
roles/flink/templates/masters.j2
roles/flink/templates/slaves.j2
streaming.yml

Add generic role to support flink cluster deployment

ARGO-626 Add Flink role

---

roles/flink/defaults/main.yml
roles/flink/templates/flink-conf.yaml.j2

Add configurable task slots on worker nodes

Flink: add configurable task slots

---

roles/consumer/templates/poem-connector.conf.j2

Update poem connector template to use the corresponding templates from private files

Update poem connector template to use the corresponding templates

---

roles/messaging_api/templates/init_roles.js.j2

Update argo-messaging mongodb roles collection

---

roles/swagger/tasks/main.yml

- create a stage folder to keep backup of data

ARGO-787 - Swagger - APIs error

---

haproxy.yml
roles/haproxy/handlers/main.yml
roles/haproxy/tasks/main.yml
roles/haproxy/templates/haproxy_template.cfg.j2
roles/has_certificate/tasks/main.yml
roles/rsyslog/handlers/main.yml
roles/rsyslog/tasks/main.yml
roles/rsyslog/templates/rsyslog.j2

haproxy first steps implementation

HA for AMS 

---

roles/mongodb/templates/init_roles.js.j2

Add role for accessing user information by providing user's token (for service admins)

Add role for ams request: get user by token

---

roles/messaging_api/tasks/deploy.yml
roles/messaging_api/templates/check-metrics.sh.j2

Add a cron-job for checking metrics in ams node

Add check-metrics cron job

---

roles/alerta/tasks/deploy.yml
roles/alerta/templates/alerta-mailer.service.env.j2

Declare enviroment variable required for alerta-mailer service

Add alerta-mailer service env options

---

gen_certs.yml
haproxy.yml
messaging_api_cluster.yml
roles/basic_utils/tasks/main.yml
roles/firewall/defaults/main.yml
roles/firewall/tasks/centos7.yml
roles/gen_cert/defaults/main.yml
roles/gen_cert/tasks/main.yml
roles/gen_priv_hosts/tasks/main.yml
roles/gen_priv_hosts/templates/hosts.j2
roles/haproxy/defaults/main.yml
roles/haproxy/templates/haproxy_template.cfg.j2
roles/has_certificate/tasks/main.yml
roles/kafka/defaults/main.yml
roles/kafka/templates/server.properties.j2
roles/messaging_api/templates/config.json.j2
roles/selinux/tasks/main.yml
roles/utils/tasks/main.yml
roles/zookeeper/defaults/main.yml
roles/zookeeper/templates/zoo.cfg.j2

ARGO-957 Refactor for msg cluster setup

---

roles/firewall/defaults/main.yml

Remove default value for variable zones in firewall role

Remove default zone configuration from firewall

---

roles/poem/tasks/main.yml
roles/poem/templates/poem.ini.j2

AO-295: POEM Ansible playbook changes

---

roles/alerta/tasks/deploy.yml

Install supervisord through yum instead of pip

Install supervisord through yum

---

roles/alerta/templates/ssl.conf.j2

Remove SSLv3 support
Remove RC4 cipher
Enable Forward Secrecy support
Enable HSTS

Configure alerta ssl parameters.

---

roles/poem/templates/ssl.conf.j2

* Removed a rewrite rule  with 404 result
* Removed SSLv3
* Removed RC4
* Enabled Forward Secrecy Support
* Enabled HSTS
* Disabled  X-Frame-Options. The server didn't return an X-Frame-Options header which means that this website could be at risk of a clickjacking attack.

ARGO-1010: poem audit action to move to grade A+

---

roles/webui/defaults/main.yml
roles/webui/tasks/main.yml
roles/webui/templates/lavoisier-hidden.properties.j2
roles/webui/templates/lavoisier-service.properties.j2

enabled https to lavoisier-hidden.

[ARGO-1006]: web-ui audit actions to make grade A+.

---

roles/webui/tasks/main.yml
roles/webui/templates/lavoisier-service.properties.j2

Until now we used to download the zip file from the repo. BUT the zip file is cached and we dont get the latest changes. Instead of this process we use the git ansible commant
with force=yes because we update the values of some properties files.

Update git process.

---

roles/alerta/defaults/main.yml
roles/alerta/templates/revaliases.j2
roles/alerta/templates/ssmtp.conf.j2

[WIP] Alerta mail

---

roles/haproxy/templates/haproxy_template.cfg.j2

Fix stats configuration to use https

Fix haproxy stats configuration

---

ce_comp_setup.yml
roles/ce_comp/handlers/main.yml
roles/ce_comp/tasks/main.yml
roles/ce_comp/templates/conf.template.j2

Comparison script setup playbook.

ARGO-1058 Comparison script set up

---

roles/alerta/defaults/main.yml
roles/alerta/tasks/deploy.yml
roles/alerta/templates/alerta-mailer.conf.j2
roles/alerta/templates/argo-alert.conf.j2
roles/alerta/templates/housekeepingAlert.js
roles/alerta/templates/supervisord.conf.j2

- Unify argo-alert and alert-mailer configuration per tenant
- Establish alert-mailer configurations per tenant
- Establish independent execution of alert-mailer (with specific conf) for each tenant through supervisord
- Update alerta-mailer and argo-alert templates with latest configuration parameters
- Refactor ssmtp parameters (keep only necessary ones)
- Add certificate and or password parameters for using argo-alert-rulegen with either certificate access or basic auth

ARGO-1088 Update configuration for alerta deployment

---

roles/haproxy/handlers/main.yml
roles/haproxy/tasks/main.yml
roles/haproxy/templates/rsyslog_haproxy.conf.j2

Configure haproxy logging using rsyslog service conf file

ARGO-1115 Configure haproxy logging

---

roles/alerta/defaults/main.yml
roles/alerta/templates/alerta-mailer.conf.j2

- Fix jinja template for mailer configuration (parameter for html template)
- Fix typo in default declaration

Fix html template option in mailer conf

---

roles/kafka/defaults/main.yml

Increase kafka default time retention policy to 7 days.
Remove size retention policy

Increase kafka default time retention policy.

---

roles/alerta/templates/alerta-mailer.conf.j2

Fix html template var in alerta role

Fix html template var in alerta role

---

commons/.yamllint
commons/README.md
commons/defaults/main.yml
commons/handlers/main.yml
commons/meta/main.yml
commons/molecule/default/Dockerfile.j2
commons/molecule/default/INSTALL.rst
commons/molecule/default/molecule.yml
commons/molecule/default/playbook.yml
commons/molecule/default/tests/test_default.py
commons/tasks/firewall.yml
commons/tasks/main.yml
commons/vars/main.yml
requirements.txt

- Add commons rule
- Add firewalls task
- Add molecule support

Add firewall task to commons rule

---

poem.yml

Add poem playbook

---

poem.yml
roles/commons/defaults/main.yml
roles/commons/handlers/main.yml
roles/commons/tasks/basic_utils.yml
roles/commons/tasks/fail2ban.yml
roles/commons/templates/etc/fail2ban/fail2ban.local.j2
roles/commons/templates/etc/fail2ban/jail.local.j2
roles/commons/vars/main.yml
roles/httpd/defaults/main.yml
roles/httpd/handlers/main.yml
roles/httpd/tasks/main.yml
roles/httpd/templates/httpd.conf.j2
roles/httpd/templates/ssl.conf.j2

Add fail2ban functionality with default settings.

Add fail2ban

---

roles/commons/molecule/default/playbook.yml
roles/haproxy/handlers/main.yml
roles/haproxy/molecule/default/playbook.yml
roles/haproxy/tasks/haproxy.yml
roles/haproxy/tasks/rsyslog.yml
roles/httpd/tasks/main.yml
roles/monbox/.yamllint
roles/monbox/defaults/main.yml
roles/monbox/handlers/main.yml
roles/monbox/meta/main.yml
roles/monbox/molecule/default/Dockerfile.j2
roles/monbox/molecule/default/INSTALL.rst
roles/monbox/molecule/default/molecule.yml
roles/monbox/molecule/default/playbook.yml
roles/monbox/molecule/default/tests/test_default.py
roles/monbox/tasks/config.yml
roles/monbox/tasks/deploy.yml
roles/monbox/vars/main.yml
roles/mongodb/tasks/main.yml
roles/poem/tasks/main.yml

Add molecule support for
- monbox
Apply Linting on roles:
- commons
- monbox
- poem
- mongodb
- haproxy
- httpd

Lint previous roles

---

roles/webapi/templates/init_roles.js.j2

Update argo-web-api role initialization after implementation of Latest Metric Data api call

ARGO-545 Update ansible web-api role with latest metrics resource

---

roles/alerta/templates/alerta.conf.j2
roles/alerta/templates/non-ssl.conf.j2
roles/alerta/templates/ssl.conf.j2
roles/consumer/templates/global.conf.j2

added {{inventory_hostname}} instead'

Remove undefined www_url form alerta.conf, non-ssl.conf ssl.conf .

---

roles/ams/templates/db_init_roles.js.j2

Add Missing roles for AckDeadline api action

AO-468 Add modifyAckDeadline role in ansible setup for AMS

---

install.yml

add monbox role to install

---

roles/mongodb/defaults/main.yml
roles/mongodb/files/root/mongo_rotate.sh
roles/mongodb/tasks/main.yml

- Add mongo_rotate.sh script which:
-- Executes mongodb admin logrotate command
-- Archives today's log in gzipped tar
-- Removes archives older than a week
- Add daily cronjob for mongo_rotate.sh

ARGO-1771 Create mongodb log rotation cron

---

roles/webapi/tasks/deploy.yml

 ARGO-1781 Deploy web-api: fix file mode in task

---

install.yml
roles/commons/README.md
roles/commons/defaults/main.yml
roles/commons/files/etc/yum.repos.d/mongodb-org-4.0.repo
roles/commons/tasks/repos.yml
roles/mongodb/README.md
roles/mongodb/defaults/main.yml
roles/mongodb/tasks/main.yml

- Modify mongodb and commons roles to support mongodb 4.x versions
- Clean/Fix install.yml playbook idendation

ARGO-1858 Support deployment of mongodb 4.x

---

install.yml
roles/cloudera_manager/tasks/main.yml

Now used the [postgresql_db](https://docs.ansible.com/ansible/latest/modules/postgresql_db_module.html) and [postgresql_user](https://docs.ansible.com/ansible/latest/modules/postgresql_user_module.html) to avoid postgreSQL problems.

DEVOPS-37 Migration tests of the role cloudera_manager in Ansible 2.9.3

---

roles/swagger/templates/index.html.j2

Fixed div #395 

---

update.yml

Add tasks to update the ams script also when we update the argo-api-authn package

DEVOPS-162 Update scripts

---

roles/ams/tasks/rollback.yml
roles/ams/tasks/update.yml
rollback.yml
update.yml

Add ams update and rollback tasks

DEVOPS-163 Add ams update and rollback tasks

---

icinga-agent.yml
install.yml
roles/icinga/README.md
roles/icinga/defaults/main.yml
roles/icinga/handlers/main.yml
roles/icinga/tasks/agent.yml
roles/icinga/tasks/common.yml
roles/icinga/tasks/common_Debian.yml
roles/icinga/tasks/common_RedHat.yml
roles/icinga/tasks/main.yml
roles/icinga/templates/icinga2-agent-kickstart.bash.j2

Ansible role for the installation of Icinga agent on the Debian GNU/Linux 8,9 and CentOS 7.
By default, it establish communication with `icinga.argo.grnet.gr` but this can easily be changed with the variable `icinga_master_domain`.
Tested : 
About current Firewall.
===================
**Attention!** When we run this role we don't want to change the current state of firewall, but just add the specific new rules for the communication of Icinga Agent. That's why this small change in the `commons/tasks/firewall.yml` task.
Usage
=======
**Important note :**
**Icinga agent needs to communicate at a specific port with Icinga Master. For this reason, you must adjust the respective firewall of your machines to allow this connection.**
* However, in our case, if you run the `firewall` task from the …

Icinga Agent role.

---

requirements.txt

Update ansible version to 2.9.11 in requirements txt

bump ansible version in requirements

---

requirements.txt
roles/swagger/tasks/apache_config.yml

Devel to Master

---

roles/httpd/templates/ssl.conf.j2

SSL jinja template needed this if statement to add the specified CA chain file

Fix ssl.conf template

---

roles/ams/tasks/deploy.yml
roles/push-server/tasks/push-server-setup.yml

Update the AMS role to also provide the CA of the respective push server in order to achieve TLS mutual authentication

AMS role update to include push server CA

---

roles/argo-api-authn/tasks/update.yml
roles/push-server/tasks/update.yml

Update the update tasks for authn and push server to explicitly call a restart action on the respective services.

ARGO-2735 Authn & Push server update role

---

install.yml
roles/commons/defaults/main.yml
roles/commons/tasks/cert.yml
roles/haproxy/defaults/main.yml
roles/haproxy/templates/haproxy_template.cfg.j2
roles/mongodb/templates/db_rs_members.js.j2

Update mongodb role to honor a new variable, is_arbiter
Also updated the cert role to check for a new variable requires_cert since some hosts don't need cert

ARGO-2793 Update mongodb ansible role to include arbiter node

---

roles/commons/handlers/main.yml
roles/commons/tasks/rsyslog.yml
roles/commons/templates/50_client_remote.conf.j2

DEVOPS-392  Update rsyslog client Ansible role

---

roles/commons/files/etc/yum.repos.d/cloudera-kafka.repo
roles/commons/files/etc/yum.repos.d/cloudera.repo

DEVOPS-403: Disable cloudera repositories.

---

install.yml
roles/eseal/README.md
roles/eseal/defaults/main.yml
roles/eseal/files/etc/logrotate.d/eseal
roles/eseal/files/etc/rsyslog.d/eseal.conf
roles/eseal/handlers/main.yml
roles/eseal/meta/main.yml
roles/eseal/tasks/main.yml
roles/eseal/templates/application.properties.j2
roles/eseal/templates/eseal.service.j2

* * [X] Create `eseal` user and group.
* * [X] Create `eseal.service` file.
* * [X] Create rsyslog filter in order to redirect logs to a separate file ( `/var/log/eseal/*` )
* * [X] Create logrotate configuration
* * [X] Download **.jar** from the latest successful Jenkins artifact. :warning:  
* * [X] Default JAR location : `/var/opt/eseal`
* * [X] Default configuration directory: `/etc/eseal/conf.d`
* * [X] API checks.
-------
Demo :
* https://snf-18613.ok-kno.grnetcloud.net/api/v1/validation/validateDocument
* https://snf-18613.ok-kno.grnetcloud.net/api/v1/signing/remoteSignDocument

DEVOPS-411: E-SEAL role.

---

roles/eseal/README.md
roles/eseal/files/etc/logrotate.d/eseal
roles/eseal/handlers/main.yml
roles/eseal/tasks/main.yml
roles/eseal/templates/application.properties.j2
roles/eseal/templates/eseal.service.j2

ESEAL Improvements.

---

roles/eseal/defaults/main.yml
roles/eseal/tasks/main.yml
roles/eseal/templates/application.properties.j2

DEVOPS-448: Update variables.

---

roles/eseal/defaults/main.yml
roles/eseal/templates/application.properties.j2

Fix ESEAL variables.

---

roles/eseal/tasks/main.yml

Fix backup.

---

roles/eseal/defaults/main.yml

Fix eseal_tsa_harica_url variable.

---

roles/commons/tasks/repos.yml
roles/commons/templates/etc/rsyslog.d/50_client_remote.conf.j2
roles/commons/templates/rsyslog.conf.j2

DEVOPS-443 Rsyslog official stable repository.

---

install.yml
roles/backup_mysql/README.md
roles/backup_mysql/defaults/main.yml
roles/backup_mysql/tasks/backup.yml
roles/backup_mysql/tasks/main.yml
roles/backup_mysql/vars/Debian.yml
roles/backup_mysql/vars/RedHat.yml
roles/backup_mysql/vars/main.yml

DEVOPS-419: MySQL backup.

---

install.yml

Add apache_certs tag.

---

roles/eseal/tasks/main.yml

Added retry & delay for API calls.

---

roles/haproxy/tasks/haproxy.yml

HAPRoxy: Added some tags.

---

roles/kafka/templates/etc/systemd/system/kafka.service.j2
roles/kafka/templates/log4j.properties.j2
roles/kafka/templates/server.properties.j2
roles/zookeeper/tasks/zookeeper.yml

* * [X] roles/kafka/templates/server.properties.j2
* * [X] roles/kafka/templates/log4j.properties.j2
* * [X] roles/kafka/templates/etc/systemd/system/kafka.service.j2
--------
Checking of daily logs..

Fix Zookeeper & Kafka logs and configuration.

---

roles/icinga_agent/README.md
roles/icinga_agent/defaults/main.yml
roles/icinga_agent/tasks/agent.yml
roles/icinga_agent/tasks/common_RedHat.yml
roles/icinga_agent/templates/icinga2-agent-kickstart.bash.j2

Fixed Icinga agent variables

---

roles/eseal/files/etc/rsyslog.d/eseal.conf
roles/eseal/tasks/main.yml
roles/eseal/templates/etc/rsyslog.d/70_eseal.conf.j2

* https://github.com/ARGOeu/argo-ansible/pull/475
* https://github.com/ARGOeu/argo-ansible/pull/476
* https://github.com/ARGOeu/argo-ansible/pull/477

ESEAL: Rsyslog improvements.

---

install.yml
roles/commons/defaults/main.yml
roles/commons/tasks/selinux.yml

* https://github.com/grnet/argo-ansible-deploy/pull/352

DEVOPS-457 SELinux disable task.

---

roles/ams/tasks/deploy.yml

Added some tags in deploy tasks:

Added tags: ams_package & ams_certs

---

install.yml
roles/argo-api-authn/tasks/authn-setup.yml

roles/argo-api-authn: `authn-scripts-cert` tag.

---

roles/haproxy/README.md

Update README about haproxy probe.

---

roles/apache/tasks/configuration.yml
roles/apache/tasks/install.yml
roles/apache/tasks/main.yml

Apache: Add tags.

---

roles/ams/templates/etc/rsyslog.d/61_ams.conf.j2

Rsyslog fix: syslogtag => programname.

---

roles/icinga_agent/tasks/common_RedHat.yml
roles/mongodb/handlers/main.yml
roles/mongodb/tasks/main.yml

DEVOPS-521 : MongoDB Icinga agent.

---

roles/commons/tasks/firewall.yml

<details>
<summary>Before :x:  </summary>
```bash
firewall-cmd --get-active-zones
internal
interfaces: eth1
public
interfaces: eth0 eth2
icinga
sources: 8**.***.***.**0/32
firewall-cmd --zone=internal --list-all
internal (active)
target: default
icmp-block-inversion: no
interfaces: eth1
sources: 
services: dhcpv6-client mdns mongodb samba-client ssh
ports: 
protocols: 
masquerade: no
forward-ports: 
source-ports: 
icmp-blocks: 
rich rules: 
firewall-cmd --zone=icinga --list-all
icinga (active)
target: default
icmp-block-inversion: no
interfaces: 
sources: 8**.***.***.**0/32
services: icinga_agent
ports: 
protocols: 
masquerade: no
forward-ports: 
source-ports: 
icmp-blocks: 
rich rules: 
firewall-cmd --zone=public --list-all
public (active)
target: default
icmp-block-inversion: no …
```

commons/firewall: Disabled public OpenSSH access.

---

roles/commons/README.md
roles/commons/tasks/firewall.yml

Run with more confidence and without stress. :call_me_hand: 
=========================================
-----------------------------------------------------------------
Run example :zap: 
=================
```bash
ansible-playbook -i test-intentory argo-ansible/install.yml -vv --tags="create_new_zones, add_services_to_zones, add_sources_to_zones, remove_ssh_from_public"
```
<details>
<summary>Output :page_facing_up:  </summary>
```bash
TASK [commons : Create firewall new zones] **********************************************************************
task path: /ansible/argo-ansible-deploy/argo-ansible/roles/commons/tasks/firewall.yml:46
ok: [exampleVM] => (item=icinga) => changed=false 
ansible_loop_var: item
cmd:
- firewall-cmd
- --permanent
- --new-zone=icinga
delta: '0:00:00.636767'
end: …
```

commons/tasks/firewall.yml: Added tags.

---

install.yml
roles/commons/README.md
roles/commons/defaults/main.yml
roles/commons/tasks/firewall.yml
roles/kafka/README.md
roles/kafka/defaults/main.yml
roles/monbox/README.md
roles/swagger/README.md
roles/webapi/README.md
roles/zookeeper/defaults/main.yml

- Refactor firewall role
- Break firewall variables to basic and extra
- Update readme.md

AO-629 Refactor Ansible

---

accounting-playbook.yml
roles/accounting/README.md
roles/accounting/defaults/main.yml
roles/accounting/files/etc/logrotate.d/accounting
roles/accounting/handlers/main.yml
roles/accounting/meta/main.yml
roles/accounting/tasks/main.yml
roles/accounting/templates/accounting.service.j2
roles/accounting/templates/etc/rsyslog.d/71_accounting.conf.j2

Related
=========================
* https://github.com/grnet/argo-ansible-deploy/pull/366
* https://github.com/ARGOeu/ARGO-accounting/pull/18

DEVOPS-573 Add Accounting role.

---

roles/accounting/defaults/main.yml
roles/accounting/templates/accounting.service.j2

Related
=========================================
* https://github.com/grnet/argo-ansible-deploy/pull/375

DEVOPS-591 Added Quarkus OIDC & Keycloak parameters.

---

roles/accounting/defaults/main.yml
roles/accounting/templates/accounting.service.j2

Related
=========================================
* https://github.com/ARGOeu/argo-ansible/pull/504
* https://github.com/ARGOeu/ARGO-accounting/pull/22

DEVOPS-593 : OIDC Authentication parameters.

---

roles/ams/tasks/deploy.yml
roles/ams/tasks/init_db.yml
roles/ams/templates/config.json.j2

AMS: Small improvements.

---

roles/accounting/defaults/main.yml

Change default value of quarkus authorization to false

Change accounting auth default value to false

---

argo-status-pages.yml
roles/argo_status_pages/defaults/main.yml
roles/argo_status_pages/handlers/main.yml
roles/argo_status_pages/tasks/deploy.yml
roles/argo_status_pages/tasks/main.yml

Add ansible role for argo-status-pages project

Introduce argo-status-pages

---

accounting-playbook.yml
roles/accounting/tasks/accounting.yml
roles/accounting/tasks/oidc_client.yml

Fix `:` in tag names in accounting roles/playbook

Fix double colons in tags in accounting tasks

---

roles/rseval/files/.env
roles/rseval/tasks/deploy.yml
rseval-playbook.yml

Update rseval role and add rseval playbook

---

argo-status-pages.yml

Signed-off-by: Kostis Triantafyllakis <ctriant@admin.grnet.gr>

Add icinga to aro-status-pages

---

roles/rseval/tasks/deploy.yml
roles/rseval/templates/supervisord.conf.j2

Create /var/log/rseval-stream directory for job logs and configure supervisord jobs to log there

Update rseval job log destination

---

roles/accounting/defaults/main.yml
roles/accounting/tasks/accounting.yml
roles/accounting/templates/accounting.service.j2

We have declared some ansible parameters that are no longer useful in Accounting Service. Therefore, we have removed them.

Remove redundant parameters

---

roles/httpd/defaults/main.yml
roles/httpd/templates/httpd.conf.j2
roles/httpd/templates/ssl.conf.j2

Add variables for configuring ports for
- listen http
- listen https

apache role make listen ports configurable

---

roles/quarkus-api/README.md
roles/quarkus-api/tasks/quarkus-api.yml

The new task is responsible for retrieving a configuration file from a specific url and inserting it into a specific directory.

Add a new task in pidmr role

---

cat-playbook.yml

Add frontend deployment task in existing cat-api-playbook.yml
Rename cat-api-playbook.yml to cat-playbook.yml since it contains both the api and ui deployment

CAT-37 Make cat plabook include frontend as well

---

roles/argo_status_pages/tasks/deploy.yml

Change the build directory for argo-status-page application

Update argo-status-pages role

---

roles/commons/files/etc/yum.repos.d/mariadb.repo

Update repo for mariadb 10.11 LTS version

AO-864 Upgrade mariadb repo to 10.11 version
